import type { Blueprint, FeatureManifest, TechStack } from '../../types/factory';
import type { SolutionTreeNode } from './types';

export interface RootFilesInput {
  blueprint: Blueprint;
  projectName: string;
  lang: string;
  useEnvFile: boolean;
  customEnvVars?: Array<{ key: string; value: string; description?: string }>;
  activeFeatures: FeatureManifest[];
  selectedStack: TechStack | undefined;
}

/**
 * Solution-level files: language build file (pom/go.mod/Cargo/pubspec/...), .env,
 * .sln, VS Code workspace/tasks/launch, setup-ide.sh, README, editorconfig.
 * Extracted verbatim from ProjectService.generateSolutionPreview (indentation kept
 * so multi-line template literals stay byte-identical).
 */
export function buildRootFiles(input: RootFilesInput) {
  const { blueprint, projectName, lang, useEnvFile, customEnvVars, activeFeatures, selectedStack } = input;
    // Identifier-safe forms of the project name for package/module names
    // (e.g. "My App-2" -> Java "myapp2", Dart "my_app_2"); invalid names break
    // javac / `dart pub get` respectively.
    const javaPackageBase =
      projectName.toLowerCase().replace(/[^a-z0-9.]/g, '').split('.').filter(Boolean)
        .map((seg) => (/^[0-9]/.test(seg) ? `_${seg}` : seg)).join('.') || 'app';
    const dartPackageName = (() => {
      const n = projectName.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
      return !n ? 'app' : /^[0-9]/.test(n) ? `app_${n}` : n;
    })();
    const goModulePath = projectName.toLowerCase().replace(/[^a-z0-9._-]/g, '-');

    // Language-specific root files
    let buildFileName = `${projectName}.sln`;
    let buildFileSnippet = `Microsoft Visual Studio Solution File, Format Version 12.00`;
    let buildFileLang = 'plaintext';

    if (lang === 'java') {
      buildFileName = 'pom.xml';
      // Aggregator POM: `mvn compile` at the root builds every module.
      const modulesXml = blueprint.projects.map((p) => `    <module>src/${p.name}</module>`).join('\n');
      buildFileSnippet = `<project xmlns="http://maven.apache.org/POM/4.0.0">\n  <modelVersion>4.0.0</modelVersion>\n  <groupId>com.acme</groupId>\n  <artifactId>${projectName.toLowerCase().replace(/[^a-z0-9.-]/g, '-')}</artifactId>\n  <version>1.0.0-SNAPSHOT</version>\n  <packaging>pom</packaging>\n  <modules>\n${modulesXml}\n  </modules>\n</project>`;
      buildFileLang = 'xml';
    } else if (lang === 'go') {
      buildFileName = 'go.mod';
      buildFileSnippet = `module github.com/acme/${goModulePath}\n\ngo 1.22`;
      buildFileLang = 'plaintext';
    } else if (lang === 'rust') {
      // Phase 20: virtual manifest — membros explícitos (cada projeto tem Cargo.toml
      // próprio + src/lib.rs). Sem deps externas: build offline-capaz.
      buildFileName = 'Cargo.toml';
      buildFileSnippet = `[workspace]\nresolver = "2"\nmembers = [${blueprint.projects.map((p) => `"src/${p.name}"`).join(', ')}]\n`;
      buildFileLang = 'toml';
    } else if (lang === 'python') {
      buildFileName = 'pyproject.toml';
      buildFileSnippet = `[tool.poetry]\nname = "${projectName.toLowerCase()}"\nversion = "0.1.0"\ndescription = "Generated by Software Factory"\n\n[tool.poetry.dependencies]\npython = "^3.12"\nfastapi = "^0.111.0"`;
      buildFileLang = 'toml';
    } else if (lang === 'typescript') {
      buildFileName = 'package.json';
      buildFileSnippet = `{\n  "name": "${projectName.toLowerCase()}",\n  "version": "1.0.0",\n  "type": "module",\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build"\n  }\n}`;
      buildFileLang = 'json';
    } else if (lang === 'kotlin') {
      buildFileName = 'build.gradle.kts';
      buildFileSnippet = `plugins {\n    kotlin("jvm") version "2.0.0"\n    id("io.ktor.plugin") version "2.3.11"\n}`;
      buildFileLang = 'kotlin';
    } else if (lang === 'dart') {
      buildFileName = 'pubspec.yaml';
      buildFileSnippet = `name: ${dartPackageName}\ndescription: Flutter Multiplatform Application\nversion: 1.0.0+1\nenvironment:\n  sdk: '>=3.4.0 <4.0.0'`;
      buildFileLang = 'yaml';
    }

    const defaultVars = customEnvVars && customEnvVars.length > 0 ? customEnvVars : [
      { key: 'PORT', value: '5000', description: 'HTTP Server Listening Port' },
      { key: 'DATABASE_URL', value: 'postgresql://admin:secret@localhost:5432/factory_db', description: 'Primary Database Connection String' },
      { key: 'JWT_SECRET', value: 'super-secret-jwt-key-32-chars-long!', description: 'HMAC SHA256 Token Signing Secret' },
      { key: 'REDIS_URL', value: 'redis://localhost:6379', description: 'Distributed Caching Host' },
      { key: 'LOG_LEVEL', value: 'Information', description: 'Logging Verbosity Threshold' },
    ];

    const envContent = defaultVars.map((v) => `# ${v.description || ''}\n${v.key}=${v.value}`).join('\n\n');
    const envExampleContent = defaultVars.map((v) => `# ${v.description || ''}\n${v.key}=<YOUR_${v.key}_HERE>`).join('\n\n');

    // Generate Visual Studio Solution (.sln) content — Phase 7: GUIDs reais via
    // crypto.randomUUID() em vez do sequencial fake {0000...-000N}.
    // Phase 9: inclui ProjectConfigurationPlatforms — sem ele o `dotnet build`
    // passa com exit 0 sem compilar nenhum projeto (falso-positivo pego no E2E).
    const generateSlnContent = (): string => {
      const entries = blueprint.projects.map((proj) => ({
        name: proj.name,
        path: `src\\${proj.name}\\${proj.name}.csproj`,
        guid: crypto.randomUUID().toUpperCase(),
      }));
      let slnText = `Microsoft Visual Studio Solution File, Format Version 12.00\n# Visual Studio Version 17\nVisualStudioVersion = 17.0.31903.59\nMinimumVisualStudioVersion = 10.0.40219.1\n`;
      for (const e of entries) {
        const guid = `{${e.guid}}`;
        slnText += `Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "${e.name}", "${e.path}", "${guid}"\nEndProject\n`;
      }
      slnText += `Global\n\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\n\t\tDebug|Any CPU = Debug|Any CPU\n\t\tRelease|Any CPU = Release|Any CPU\n\tEndGlobalSection\n`;
      slnText += `\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\n`;
      for (const e of entries) {
        const guid = `{${e.guid}}`;
        slnText += `\t\t${guid}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\n`;
        slnText += `\t\t${guid}.Debug|Any CPU.Build.0 = Debug|Any CPU\n`;
        slnText += `\t\t${guid}.Release|Any CPU.ActiveCfg = Release|Any CPU\n`;
        slnText += `\t\t${guid}.Release|Any CPU.Build.0 = Release|Any CPU\n`;
      }
      slnText += `\tEndGlobalSection\nEndGlobal\n`;
      return slnText;
    };

    // Generate VS Code Workspace configuration
    const vscodeWorkspaceSnippet = JSON.stringify({
      folders: [
        { name: `${projectName} (Root)`, path: "." },
        { name: "Source Code", path: "src" }
      ],
      settings: {
        "files.exclude": { "**/bin": true, "**/obj": true, "**/node_modules": true, "**/.git": true },
        "editor.formatOnSave": true,
        "editor.tabSize": 2
      },
      extensions: {
        recommendations: [
          lang === 'csharp' ? "ms-dotnettools.csharp" : lang === 'rust' ? "rust-lang.rust-analyzer" : "dbaeumer.vscode-eslint",
          "esbenp.prettier-vscode",
          "ms-azuretools.vscode-docker",
          "eamodio.gitlens"
        ]
      }
    }, null, 2);

    // Generate .vscode/tasks.json
    const vscodeTasksSnippet = JSON.stringify({
      version: "2.0.0",
      tasks: [
        {
          label: "build",
          command: lang === 'csharp' ? "dotnet build" : lang === 'rust' ? "cargo build" : "npm run build",
          type: "shell",
          group: { kind: "build", isDefault: true },
          problemMatcher: lang === 'csharp' ? "$msCompile" : "$tsc"
        },
        {
          label: "test",
          command: lang === 'csharp' ? "dotnet test" : lang === 'rust' ? "cargo test" : "npm test",
          type: "shell",
          group: { kind: "test", isDefault: true }
        }
      ]
    }, null, 2);

    // Generate .vscode/launch.json
    const vscodeLaunchSnippet = JSON.stringify({
      version: "0.2.0",
      configurations: [
        {
          name: `Launch ${projectName} API`,
          type: lang === 'csharp' ? "coreclr" : "node",
          request: "launch",
          preLaunchTask: "build",
          program: lang === 'csharp' ? `\${workspaceFolder}/src/${projectName}.Api/bin/Debug/net9.0/${projectName}.Api.dll` : "\${workspaceFolder}/src/index.ts",
          args: [],
          cwd: "\${workspaceFolder}",
          stopAtEntry: false,
          env: { "ASPNETCORE_ENVIRONMENT": "Development", "NODE_ENV": "development" }
        }
      ]
    }, null, 2);

    // Shell script to setup & open IDE
    const setupIdeScript = `#!/usr/bin/env bash
# Automatically generated IDE environment launcher script for ${projectName}
echo "🚀 Initializing ${projectName} IDE workspace..."
git init
echo "✅ Git repository initialized."
${lang === 'csharp' ? 'dotnet restore' : lang === 'rust' ? 'cargo fetch' : 'npm install'}
echo "✅ Dependencies restored."
echo ""
echo "Open in your preferred IDE:"
echo " 1) VS Code:        code ."
echo " 2) VS Code Space:  code ${projectName}.code-workspace"
echo " 3) Visual Studio:  devenv ${projectName}.sln"
echo " 4) JetBrains:      rider ${projectName}.sln"
`;

    const rootFiles: SolutionTreeNode[] = [
      // Phase 9: para C# o .sln canônico é o file-sln (conteúdo completo) — sem duplicata.
      ...(buildFileName !== `${projectName}.sln` ? [{
        id: 'file-build-root', name: buildFileName, type: 'file' as const, path: buildFileName, language: buildFileLang, contentSnippet: buildFileSnippet,
      }] : []),
      { id: 'file-editorconfig', name: '.editorconfig', type: 'file', path: '.editorconfig', language: 'ini', contentSnippet: `root = true\n\n[*]\nindent_style = space\nindent_size = 2` },
      { id: 'file-readme', name: 'README.md', type: 'file', path: 'README.md', language: 'markdown', contentSnippet: `# ${projectName}\n\nGenerated by Enterprise Software Factory Platform.\nStack: ${selectedStack?.name || lang}\nArchitecture: ${blueprint.architectureStyle}\nActive Features: ${activeFeatures.map((f) => f.name).join(', ')}\n\n## Build\n\n\`\`\`bash\ndotnet restore\ndotnet build ${projectName}.sln -c Release\ndotnet test ${projectName}.sln\n\`\`\`` },
      { id: 'file-vscode-ws', name: `${projectName}.code-workspace`, type: 'file', path: `${projectName}.code-workspace`, language: 'json', contentSnippet: vscodeWorkspaceSnippet },
      { id: 'file-sln', name: `${projectName}.sln`, type: 'file', path: `${projectName}.sln`, language: 'xml', contentSnippet: generateSlnContent() },
      { id: 'file-setup-sh', name: 'setup-ide.sh', type: 'file', path: 'setup-ide.sh', language: 'bash', contentSnippet: setupIdeScript },
      ...(lang === 'csharp' ? [
        { id: 'file-msbuild-props', name: 'Directory.Build.props', type: 'file' as const, path: 'Directory.Build.props', language: 'xml', contentSnippet: `<Project>\n  <PropertyGroup>\n    <Nullable>enable</Nullable>\n    <ImplicitUsings>enable</ImplicitUsings>\n    <EnableNETAnalyzers>true</EnableNETAnalyzers>\n    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>\n  </PropertyGroup>\n</Project>` },
        { id: 'file-global-json', name: 'global.json', type: 'file' as const, path: 'global.json', language: 'json', contentSnippet: `{\n  "sdk": {\n    "version": "9.0.100",\n    "rollForward": "latestFeature"\n  }\n}` },
      ] : []),
    ];

    if (useEnvFile) {
      rootFiles.push(
        { id: 'file-env', name: '.env', type: 'file', path: '.env', language: 'ini', contentSnippet: envContent },
        { id: 'file-env-example', name: '.env.example', type: 'file', path: '.env.example', language: 'ini', contentSnippet: envExampleContent }
      );
    } else {
      rootFiles.push({
        id: 'file-launch-settings',
        name: 'appsettings.json',
        type: 'file',
        path: 'appsettings.json',
        language: 'json',
        contentSnippet: `{\n  "Logging": {\n    "LogLevel": {\n      "Default": "Information"\n    }\n  },\n  "AllowedHosts": "*"\n}`,
      });
    }

    return { javaPackageBase, vscodeTasksSnippet, vscodeLaunchSnippet, rootFiles };
}
