// @vitest-environment node
import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readdirSync, readFileSync, statSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, relative, sep } from 'node:path';
import { ProjectService, type SolutionTreeNode } from './projectService';
import { initialBlueprints } from './mockSeedData';

const PACK_NAME = 'Acme.Golden';
const SHORT_NAME = 'sffactory-clean';

function hasDotnetSdk(): boolean {
  try {
    execFileSync('dotnet', ['--version'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function templateJson(): string {
  return JSON.stringify(
    {
      $schema: 'http://json.schemastore.org/template',
      author: 'Software Factory',
      classifications: ['Clean Architecture', '.NET', 'WebApi'],
      identity: 'SFFactory.CleanApi',
      groupIdentity: 'SFFactory.CleanApi',
      name: 'Software Factory Clean API (.NET 9)',
      description: 'Golden path: Clean Architecture .NET 9 API generated by Software Factory (rule-2 BaseApiController, rule-3 repository split, xUnit).',
      shortName: SHORT_NAME,
      tags: { language: 'C#', type: 'solution' },
      sourceName: PACK_NAME,
      sources: [{ source: 'content/', target: '' }],
      primaryOutputs: [{ path: `${PACK_NAME}.sln` }],
    },
    null,
    2
  );
}

function writeTree(nodes: SolutionTreeNode[], root: string): void {
  for (const n of nodes) {
    const target = join(root, ...n.path.split('/'));
    if (n.type === 'file') {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, n.contentSnippet || '');
    } else if (n.children) {
      mkdirSync(target, { recursive: true });
      writeTree(n.children, root);
    }
  }
}

/** Escreve o pack (template.json + content/) num diretório. Single source: ProjectService. */
export function exportTemplatePack(dir: string): void {
  const preview = ProjectService.generateSolutionPreview(initialBlueprints[0], PACK_NAME, true);
  mkdirSync(join(dir, '.template.config'), { recursive: true });
  writeFileSync(join(dir, '.template.config', 'template.json'), templateJson());
  mkdirSync(join(dir, 'content'), { recursive: true });
  writeTree(preview.solutionTree, join(dir, 'content'));
}

function listFilesRecursive(root: string): Map<string, string> {
  const out = new Map<string, string>();
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) walk(full);
      else out.set(relative(root, full).split(sep).join('/'), readFileSync(full, 'utf-8'));
    }
  };
  walk(root);
  return out;
}

// Phase 12 E2E: install → instantiate (-n Verify.App) → build → uninstall.
// Mutates o cache de templates do usuário, com uninstall garantido em finally.
describe.skipIf(!hasDotnetSdk())('dotnet new private pack (Phase 12)', () => {
  it('installs, instantiates under a new name, and builds with zero errors', () => {
    const dir = mkdtempSync(join(tmpdir(), 'sf-tmpl-'));
    const packDir = join(dir, 'pack');
    exportTemplatePack(packDir);
    let installed = false;
    try {
      execFileSync('dotnet', ['new', 'install', packDir], { cwd: dir, stdio: 'pipe', timeout: 120000 });
      installed = true;
      const outDir = join(dir, 'out');
      execFileSync('dotnet', ['new', SHORT_NAME, '-n', 'Verify.App', '-o', outDir], { cwd: dir, stdio: 'pipe', timeout: 120000 });
      const output = execFileSync('dotnet', ['build', join(outDir, 'Verify.App.sln'), '-c', 'Release', '--nologo'], {
        cwd: dir, timeout: 240000, encoding: 'utf-8',
      }) as unknown as string;
      expect(output).toContain('Build succeeded.');
    } finally {
      if (installed) {
        try {
          execFileSync('dotnet', ['new', 'uninstall', packDir], { cwd: dir, stdio: 'pipe', timeout: 120000 });
        } catch {
          // uninstall best-effort; nunca mascara o resultado do teste
        }
      }
      rmSync(dir, { recursive: true, force: true });
    }
    expect(true).toBe(true);
  }, 420000);
});

describe('dotnet-template/ committed snapshot matches the generator (drift guard)', () => {
  it('content/ equals a fresh generateSolutionPreview (re-export on drift)', () => {
    const committed = join(process.cwd(), 'dotnet-template', 'content');
    let files: Map<string, string>;
    try {
      files = listFilesRecursive(committed);
    } catch {
      throw new Error(
        'dotnet-template/content/ missing — regenerate with: SF_EXPORT_TEMPLATE=./dotnet-template npm run test -- dotnetTemplateExport'
      );
    }
    const dir = mkdtempSync(join(tmpdir(), 'sf-tmpl-drift-'));
    try {
      const preview = ProjectService.generateSolutionPreview(initialBlueprints[0], PACK_NAME, true);
      const freshRoot = join(dir, 'content');
      mkdirSync(freshRoot, { recursive: true });
      writeTree(preview.solutionTree, freshRoot);
      const fresh = listFilesRecursive(freshRoot);
      // .sln GUIDs são randomUUID por design (Phase 7) — normaliza antes de comparar.
      // Todo o resto (estrutura, arquivos, código) deve ser byte-idêntico.
      const normalize = (s: string): string =>
        s.replace(/\{[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}\}/g, '{GUID}');
      expect([...fresh.keys()].sort()).toEqual([...files.keys()].sort());
      for (const [rel, content] of fresh) {
        expect(normalize(files.get(rel) || ''), `drift in dotnet-template/content/${rel}`).toBe(normalize(content));
      }
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

// Export manual: SF_EXPORT_TEMPLATE=./dotnet-template npm run test -- dotnetTemplateExport
describe('dotnetTemplateExport', () => {
  it('writes the pack to SF_EXPORT_TEMPLATE when set (no-op otherwise)', () => {
    const target = process.env.SF_EXPORT_TEMPLATE;
    if (!target) return;
    const dir = join(process.cwd(), target);
    rmSync(join(dir, 'content'), { recursive: true, force: true });
    exportTemplatePack(dir);
  });
});
